[ADD] mrp_stock_owner_restriction
OCA/manufacture pull request #1013
Opened 2023-04-04 12:10 UTC by AungKoKoLin1997

This module adopt the functionality of stock_owner_restriction in the manufacturing order.
Related - https://github.com/OCA/stock-logistics-workflow/pull/1231

@qrtl

2023-09-04 03:31 UTC, yostashiro commented
@AungKoKoLin1997 Can you please rebase and push?

2023-09-23 08:19 UTC, yostashiro requested changes

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        )
To make variables easier to understand.
```suggestion
        self.finished_product = self.env["product.product"].create(
            {"name": "test product", "type": "product"}
        )
        self.component = self.env["product.product"].create(
            {"name": "test component", "type": "product"}
        )
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        self.picking_type_id = self.env["stock.picking.type"].search(
```suggestion
        self.picking_type = self.env["stock.picking.type"].search(
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        self.product.invalidate_model()
```suggestion
        self.product.invalidate_model(["qty_available"])
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        )
We should apply owner restriction on the MO, or the test scenario makes little business sense (you wouldn't consume your own inventory to create a product owned by another party).
```suggestion
        )
        self.picking_type.write({"owner_restriction": "picking_partner"})
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +            {"bom_id": self.bom.id, "product_id": self.product_2.id, "product_qty": 2}
```suggestion
            {"bom_id": self.bom.id, "product_id": self.component.id, "product_qty": 1}
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +    def test_mrp_quant_assign_owner(self):
Start with asserting component quantities before production.
```suggestion
    def test_mrp_quant_assign_owner(self):
        self.assertEqual(self.component.qty_available, 250)
        self.component.invalidate_model(["qty_available"])
        self.assertEqual(
            self.component.with_context(skip_restricted_owner=True).qty_available, 500
        )
```

2023-09-23 08:19 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        )
```suggestion
        # Confirm that component inventory with owner has been consumed
        self.assertEqual(self.component.qty_available, 250)
        self.component.invalidate_model(["qty_available"])
        self.assertEqual(
            self.component.with_context(skip_restricted_owner=True).qty_available, 250
        )
```

2023-11-10 18:01 UTC, gurneyalex approved these changes

2023-11-10 18:01 UTC, gurneyalex commented on mrp_stock_owner_restriction/readme/DESCRIPTION.rst
> +This module adopts the functionality of stock_owner_restriction in the manufacturing
```suggestion
This module adapts the functionality of stock_owner_restriction in the manufacturing
```

2024-09-30 14:53 UTC, bosd commented
/ocabot rebase Would love a new runboat for func testing.

2024-10-01 02:27 UTC, AungKoKoLin1997 commented
@bosd I rerun the CI.

2024-10-01 07:20 UTC, bosd approved these changes

2024-10-16 19:01 UTC, bosd approved these changes

2024-10-17 00:53 UTC, yostashiro requested changes
I think we forgot to use the `owner_restriction` field defined in the production.

2024-10-17 00:53 UTC, yostashiro commented on mrp_stock_owner_restriction/models/mrp_production.py
> +                if owner_restriction in ("unassigned_owner", "picking_partner"):
```suggestion
                if production.owner_restriction in ("unassigned_owner", "picking_partner"):
```

2024-10-17 00:53 UTC, yostashiro commented on mrp_stock_owner_restriction/models/mrp_unbuild.py
> +        owner_restriction = self.mo_id.picking_type_id.owner_restriction
```suggestion
        owner_restriction = self.mo_id.owner_restriction
```

2024-10-17 00:53 UTC, yostashiro commented on mrp_stock_owner_restriction/models/stock_move.py
> +            return mo_to_unbuild.picking_type_id.owner_restriction
```suggestion
            return mo_to_unbuild.owner_restriction
```

2024-10-17 02:04 UTC, AungKoKoLin1997 commented on mrp_stock_owner_restriction/models/mrp_production.py
> +                if owner_restriction in ("unassigned_owner", "picking_partner"):
Done!

2024-10-17 02:05 UTC, AungKoKoLin1997 commented on mrp_stock_owner_restriction/models/stock_move.py
> +            return mo_to_unbuild.picking_type_id.owner_restriction
Done!

2024-10-17 02:05 UTC, AungKoKoLin1997 commented on mrp_stock_owner_restriction/models/mrp_unbuild.py
> +        owner_restriction = self.mo_id.picking_type_id.owner_restriction
Done!

2024-10-17 04:07 UTC, yostashiro approved these changes

2024-10-17 10:40 UTC, Dranyel-Bosd reviewed
LGTM :sparkler:

2025-01-02 13:25 UTC, bosd commented
@LoisRForgeFlow Do you have the powers to merge here? :pray:

2025-01-07 07:53 UTC, LoisRForgeFlow commented on mrp_stock_owner_restriction/__manifest__.py
> +    "installable": True,
auto install?

2025-01-07 07:53 UTC, LoisRForgeFlow commented on mrp_stock_owner_restriction/models/mrp_unbuild.py
> +    # owner_restriction = fields.Selection(related="picking_type_id.owner_restriction")
this code is commented. If you are not going to finish it, remove it and add a note in the roadmap, please.

2025-01-10 08:39 UTC, nobuQuartile commented on mrp_stock_owner_restriction/__manifest__.py
> +    "installable": True,
Thank you for your advice.
I updated the code.

2025-01-10 08:40 UTC, nobuQuartile commented on mrp_stock_owner_restriction/models/mrp_unbuild.py
> +    # owner_restriction = fields.Selection(related="picking_type_id.owner_restriction")
I updated the code.

2025-01-10 09:26 UTC, nobuQuartile commented
I will follow up on the errors that are occurring.

2025-01-20 05:16 UTC, AungKoKoLin1997 commented
@gurneyalex @LoisRForgeFlow @yostashiro @bosd @Dranyel-Bosd @nobuQuartile 
Please review my latest changes.
In my last commit, to fix the test failures during product creation, I made the test execute at the end of module loading using @tagged('post_install', '-at_install') to avoid the error 'null value in column "sale_line_warn" violates not-null constraint' when the sale module is already installed in the environment. I also used @classmethod.

2025-01-20 06:57 UTC, bosd approved these changes
Functional Review :+1

2025-01-20 07:07 UTC, yostashiro approved these changes
Thanks for the fix.

2025-01-20 07:07 UTC, yostashiro commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        )
```suggestion
        cls.finished_product = cls.env["product.product"].create(
            {"name": "test product", "type": "product"}
        )
```

2025-01-20 07:15 UTC, AungKoKoLin1997 commented on mrp_stock_owner_restriction/tests/test_mrp_stock_owner_restriction.py
> +        )
Done!

2025-01-23 08:41 UTC, LoisRForgeFlow commented
@AungKoKoLin1997 could you squash in a single commit?

2025-01-23 08:52 UTC, AungKoKoLin1997 commented
@LoisRForgeFlow Done!

2025-01-23 09:38 UTC, LoisRForgeFlow approved these changes
Thanks!

2025-01-23 09:38 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2025-01-23 09:49 UTC, merged