[14.0][IMP] mrp_subcontracting_partner_management
OCA/manufacture pull request #1105
Opened 2023-10-14 15:53 UTC by geomer198

Dependencies and module flow is updated.

2023-10-17 13:36 UTC, francesco-ooops approved these changes
LGTM

@geomer198 please squash

2023-10-18 16:27 UTC, GabbasovDinar approved these changes

2023-10-19 16:49 UTC, francesco-ooops commented
@pedrobaeza what do you think?

2023-10-19 17:02 UTC, pedrobaeza requested changes

2023-10-19 17:02 UTC, pedrobaeza commented on mrp_subcontracting_partner_management/__manifest__.py
> +    "depends": ["purchase_stock", "mrp_subcontracting_purchase", "sale_stock"],
You shouldn't change dependencies in a stable module. Do instead an extension module.

2023-10-25 18:25 UTC, geomer198 commented
@pedrobaeza Tests in the current module is broken in bridge module. I propose a solution: Can I add  in settings a parameter for the activate `mrp_subcontracting_purchase` module and change a tests with depends on installing this module.

2023-10-27 16:04 UTC, pedrobaeza commented
You can do both modules in this PR.

2023-10-30 18:22 UTC, closed without merging