[17.0][MIG] mrp_bom_tracking: Migration to 17.0
OCA/manufacture pull request #1226
Opened 2024-03-08 15:37 UTC by AndreuOForgeFlow

Standard migration

@ForgeFlow

2024-03-11 10:44 UTC, GuillemCForgeFlow requested changes
general improvements and feedback 🙂

2024-03-11 10:44 UTC, GuillemCForgeFlow commented on mrp_bom_tracking/models/mrp_bom.py
> +                    )
```suggestion
        if "product_id" in values:
            for bom_line in self:
                bom = bom_line.bom_id
                product_id = values.get("product_id")
                product = self.env["product.product"].browse(product_id)
                if product.exists():
                    message_body = template_env._render_template(
                        "mrp_bom_tracking.track_bom_template_2",
                        values={"lines": bom_line, "product_id": product},
                    )
                    bom.message_post(
                        body=message_body, subtype_id=self.env.ref("mail.mt_note").id
                    )
```
`product_id` check was already done at the beginning of the indentation, no need to do it again. Also, refactor to iterate over self, which contains the BoM lines, as before the change, it was already doing one message posting per line change. I believe this refactoring simplifies the understanding of the logic. What do you think?
I believe this is more of a general improvement, nothing related to the migration itself.

2024-03-11 10:44 UTC, GuillemCForgeFlow commented on mrp_bom_tracking/models/mrp_bom.py
> +                    )
```suggestion
        elif "product_qty" in values or "product_uom_id" in values:
            for bom_line in self:
                bom = bom_line.bom_id
                product_qty = values.get("product_qty") or bom_line.product_qty
                product_uom_id = values.get("product_uom_id")
                if product_uom_id:
                    product_uom = self.env["uom.uom"].browse(product_uom_id)
                product_uom = product_uom or bom_line.product_uom_id
                message_body = template_env._render_template(
                    "mrp_bom_tracking.track_bom_line_template",
                    values={
                        "lines": bom_line,
                        "product_qty": product_qty,
                        "product_uom_id": product_uom,
                    },
                )
                bom.message_post(
                    body=message_body, subtype_id=self.env.ref("mail.mt_note").id
                )
```
Same as above comment.

2024-03-11 10:44 UTC, GuillemCForgeFlow commented on mrp_bom_tracking/models/mrp_bom.py
> +# Copyright 2019 ForgeFlow S.L. (https://www.forgeflow.com)
```suggestion
# Copyright 2019-2024 ForgeFlow S.L. (https://www.forgeflow.com)
```
update Copyright here as well!

2024-03-11 10:44 UTC, GuillemCForgeFlow commented on mrp_bom_tracking/tests/test_mrp_bom_tracking.py
> +# Copyright 2019 ForgeFlow S.L. (https://www.forgeflow.com)
```suggestion
# Copyright 2019-2024 ForgeFlow S.L. (https://www.forgeflow.com)
```
same here.

2024-03-11 10:44 UTC, GuillemCForgeFlow commented on mrp_bom_tracking/views/bom_template.xml
> +<!-- Copyright 2019 ForgeFlow S.L. (https://www.forgeflow.com)
```suggestion
<!-- Copyright 2019-2024 ForgeFlow S.L. (https://www.forgeflow.com)
```
and here.

2024-03-11 11:22 UTC, AndreuOForgeFlow commented on mrp_bom_tracking/models/mrp_bom.py
> +# Copyright 2019 ForgeFlow S.L. (https://www.forgeflow.com)
It is not necessary to do that if we want to follow the OCA migration guidelines to v17 as seen here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-not-to-do-in-the-migration

2024-03-11 13:03 UTC, GuillemCForgeFlow approved these changes
LGTM! Thank you for the improvements 👍🏽

2024-03-25 14:02 UTC, LoisRForgeFlow commented
/ocabot migration mrp_bom_tracking

2024-03-25 14:06 UTC, LoisRForgeFlow reviewed
Tested and working good, I want to suggest one more improvement: Can you add tracking to the fields in the Miscelaneous tab too?

![image](https://github.com/OCA/manufacture/assets/23449160/bfde9820-c3cf-4850-b8ec-0f693a5affc4)

Thanks!

2024-03-26 09:55 UTC, AndreuOForgeFlow commented
> Tested and working good, I want to suggest one more improvement: Can you add tracking to the fields in the Miscelaneous tab too?
> 
> ![image](https://private-user-images.githubusercontent.com/23449160/316526994-bfde9820-c3cf-4850-b8ec-0f693a5affc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDcxODIsIm5iZiI6MTcxMTQ0Njg4MiwicGF0aCI6Ii8yMzQ0OTE2MC8zMTY1MjY5OTQtYmZkZTk4MjAtYzNjZi00ODUwLWI4ZWMtMGY2OTNhNWFmZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5NTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YzE3YzZlMjA3N2IyMDM2ZjMzNzdjMjgzZjQxOTQyNTExNzA2YmRhZTk4NzdjMTgxOTVmNTlmMzExMWYzOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Homy_ITyQya7-DGGht6jJ6h30XcciTKDyb252PxO104)
> 
> Thanks!

Done @LoisRForgeFlow!

2024-03-26 10:31 UTC, LoisRForgeFlow approved these changes
Thanks!

/ocabot merge nobump

2024-03-26 10:35 UTC, merged