[17.0][MIG] mrp_bom_location
OCA/manufacture pull request #1229
Opened 2024-03-12 12:53 UTC by CarlosVForgeFlow

Migration to 17.0

@ForgeFlow

2024-06-03 07:51 UTC, atchuthan requested changes
Minor changes required
Technical QA done :+1:

2024-06-03 07:51 UTC, atchuthan commented on mrp_bom_location/__manifest__.py
> +    "version": "17.0.1.1.1",
17.0.1.0.0

2024-06-03 08:23 UTC, CarlosVForgeFlow commented on mrp_bom_location/__manifest__.py
> +    "version": "17.0.1.1.1",
Done!

2024-06-03 09:18 UTC, atchuthan approved these changes
:+1:

2024-07-02 10:59 UTC, DavidJForgeFlow approved these changes

2024-10-23 13:43 UTC, micheledic approved these changes

2024-11-14 08:18 UTC, atchuthan commented
@OCA/manufacturing-maintainers This PR has approved label and ready for merge.  Please check it.  Thanks

2025-04-20 12:45 UTC, closed without merging