[16] ADD mrp_workcenter_workorder_link
OCA/manufacture pull request #1260
Opened 2024-04-11 09:43 UTC by florian-dacosta

Module that improve mainly workcenter views to be able to navigate and see attached workorders.
Add button on workcenter tree view to see related ongoing workorders
Add button on form workcenter view to see the related ongoing workorders + add a one2many also on form view

2024-06-17 12:52 UTC, bealdav approved these changes
LGTM, thanks

2025-03-02 13:34 UTC, rvalyi requested changes
The license header in the files is LGPL while it's AGPL in the manifest. It should be consistent...

2025-03-04 10:30 UTC, florian-dacosta commented
Thanks for pointing this out @rvalyi, I fixed the files, it is agpl indeed.

2025-03-08 02:22 UTC, rvalyi approved these changes
LGTM; trivial module

2025-03-08 02:23 UTC, rvalyi commented
/ocabot merge nobump

2025-03-08 03:50 UTC, merged