Adding mrp_group module
OCA/manufacture pull request #1291
Opened 2024-06-25 07:32 UTC by ZestyBeanz-Odoo

2024-07-24 09:56 UTC, quentinDupont commented
Hello ! thank for your work
I'm not sure to understand the uses cases
But it seems to be near the new module `mrp_bom_tag` that i develop and that have been merged : https://github.com/OCA/manufacture/tree/16.0/mrp_bom_tag

Your description is about Libreoffice report, mrp_production etc. but it doesn't feet the code you wrote. 
And the module name "mro_group" is not explicit enough in my opinion

2024-07-24 09:56 UTC, quentinDupont requested changes
Hello ! thank for your work
I'm not sure to understand the uses cases
But it seems to be near the new module `mrp_bom_tag` that i develop and that have been merged : https://github.com/OCA/manufacture/tree/16.0/mrp_bom_tag

Your description is about Libreoffice report, mrp_production etc. but it doesn't feet the code you wrote. 
And the module name "mro_group" is not explicit enough in my opinion

2024-07-30 09:34 UTC, ZestyBeanz-Odoo commented
> But it seems to be near the new module `mrp_bom_tag` that i develop and that have been merged : https://github.com/OCA/manufacture/tree/16.0/mrp_bom_tag

Hello,

Thank you for your feedback and observations!

It looks like you’re referring to a module mrp_bom_tag which is focused on manufacturing and bill of materials (BoM) tagging. I understand you’re interested in extending similar features to other parts of the Manufacturing module, such as the Manufacturing Orders (MO).Extending features from mrp_bom_tag to Manufacturing Orders is definitely feasible and can be valuable for providing consistent tagging or reporting functionalities across different aspects of manufacturing.

If you’re interested in collaborating on this, please let me know. We can discuss the specific requirements and work on integrating these features into other parts of the Manufacturing module together.

2024-07-30 14:12 UTC, quentinDupont commented
> > But it seems to be near the new module `mrp_bom_tag` that i develop and that have been merged : https://github.com/OCA/manufacture/tree/16.0/mrp_bom_tag
> 
> Hello,
> 
> Thank you for your feedback and observations!
> 
> It looks like you’re referring to a module mrp_bom_tag which is focused on manufacturing and bill of materials (BoM) tagging. I understand you’re interested in extending similar features to other parts of the Manufacturing module, such as the Manufacturing Orders (MO).Extending features from mrp_bom_tag to Manufacturing Orders is definitely feasible and can be valuable for providing consistent tagging or reporting functionalities across different aspects of manufacturing.
> 
> If you’re interested in collaborating on this, please let me know. We can discuss the specific requirements and work on integrating these features into other parts of the Manufacturing module together.

Yep lets do this, you can send me an email : quentin.dupont@grap.coop :)

2025-01-05 12:41 UTC, closed without merging