[16.0][ADD] mrp_bom_priority
OCA/manufacture pull request #1407
Opened 2024-11-28 14:11 UTC by quentinDupont

Adds priority to helps prioritize BoM.

![mrp_bom_view_tree](https://github.com/user-attachments/assets/5217f132-44e6-456a-86b4-4270a9029545)
![mrp_bom_view_form](https://github.com/user-attachments/assets/2567ea39-989a-4994-ae17-dc86929177c5)

2025-03-31 12:41 UTC, legalsylvain approved these changes
General review. LGTM.

some remarks inline. I wonder if we should better change the order in the code, to make it working everywhere. 

for the time being, here is the default order : sequence, id

https://github.com/odoo/odoo/blob/16.0/addons/mrp/models/mrp_bom.py#L19

2025-03-31 12:41 UTC, legalsylvain commented on mrp_bom_priority/views/view_mrp_bom.xml
> +              <attribute name="default_order">priority desc</attribute>
default_order (or _order), make the item order by the field(s). if there are many items with the same value, the next order is "by id". that is not very user intuitive. See : 

![image](https://github.com/user-attachments/assets/46a45f12-6511-4948-add5-f9e91e660b6f)

In that case, I expect both "extra coulis" boms to be next to it.
something like that ? (not sure, just a proposal).

```suggestion
              <attribute name="default_order">priority desc, product_tmpl_id,code</attribute>
```

2025-03-31 12:41 UTC, legalsylvain commented on mrp_bom_priority/views/view_mrp_bom.xml
> +                <field name="priority" widget="priority" />
Allow user to hide the field to simplify the view, if they don't use it.

```suggestion
                <field name="priority" widget="priority" optional="show"/>
```

2025-03-31 13:17 UTC, quentinDupont commented on mrp_bom_priority/views/view_mrp_bom.xml
> +              <attribute name="default_order">priority desc</attribute>
Yep I think it makes sense !

2025-06-03 13:49 UTC, LoisRForgeFlow commented
@quentinDupont Could you squash all commits into one?

2025-06-11 10:19 UTC, quentinDupont commented
Done @LoisRForgeFlow :-)

2025-06-11 13:54 UTC, LoisRForgeFlow commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
@quentinDupont Looks like you are adding priority without any feature/behavior related to it. I would have expected to then modify the standard algorithm to find the bom to apply by default.

What is your use case?

2025-06-17 10:19 UTC, quentinDupont commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
The use case is to quickly see your favorite BoMs, the one you check or change often
No algorithm changes but priority change in tree view here : https://github.com/OCA/manufacture/pull/1407/files#diff-a9763f49357eeb3d0f9b21812afde85a545efb1d3ccbf07c5593c97d000e8765R37
Thanks for your review and time :)

2025-06-18 09:19 UTC, LoisRForgeFlow commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
I can imagine this being a bit confusing, because in the same view you have the sequence widget that it's what actually will be used to select a BoM first when manufacturing(https://github.com/odoo/odoo/blob/938b772ab60501ac7028da0edf2f66a758004363/addons/mrp/models/mrp_bom.py#L374) but that widget will not make any effect and you will see first the ones with more stars.

2025-06-24 08:13 UTC, quentinDupont commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
Indeed, I understand your point of view.
In our Odoo, we've changed the order of BoM by priority then alphabetically: a behavior that we feel is much more expected and understandable for users. But I agree that it would be nice to be taken into account when choosing a BoM at the time of manufacturing → in the ROADMAP for this module?

2025-06-25 07:53 UTC, LoisRForgeFlow commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
If you just add it to the ROADMAP and do not implement it, I won't block the PR but I won't approve it either. But I'm sure you can convince someone else.

2025-06-26 08:10 UTC, quentinDupont commented on mrp_bom_priority/models/mrp_bom.py
> +    priority = fields.Selection(
Ok so I think your criticism are relevant, I make the following changes : 
- replacing sequence in tree view → it was no longer working anyway with priority
- overriding native function to select best prioritized BoM for manufacturing (insted of their sequence) as you suggest

2025-07-02 14:15 UTC, LoisRForgeFlow reviewed
Thanks for the improvements! a comment below

2025-07-02 14:15 UTC, LoisRForgeFlow commented on mrp_bom_priority/models/mrp_bom.py
> +        """Override native function to change order"""
Maybe you can try to propose the introduction of a hook to odoo?

Otherwise the correct way to do it is by adding a hook via OCA module, see for instance this one https://github.com/OCA/stock-logistics-workflow/blob/16.0/stock_account_product_run_fifo_hook/hooks.py. We need this to keep proper inheritance, we cannot merge a module that simply overrides an standard one like this.

2025-07-02 15:34 UTC, marcelsavegnago approved these changes

2025-07-02 15:38 UTC, LoisRForgeFlow requested changes
As per https://github.com/OCA/manufacture/pull/1407#discussion_r2180176382. We cannot merge with such an override.

2025-10-28 21:38 UTC, legalsylvain commented
Hi @LoisRForgeFlow. thanks for your review. could you take a look on my last commit. I implemented a lighter code that respect inheritance.
thanks !

2025-10-29 09:10 UTC, LoisRForgeFlow approved these changes
@legalsylvain Thanks, LGTM now :+1:

2025-10-29 09:35 UTC, legalsylvain commented
Thanks for tour review !

/ocabot merge nobump

2025-10-29 09:49 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2025-10-29 10:00 UTC, merged