[17.0][FIX] mrp_multi_level: properly handle UserError in procurement.
OCA/manufacture pull request #1413
Opened 2024-12-09 16:19 UTC by RicardCForgeFlow

Small fix
AttributeError: 'UserError' object has no attribute 'name'.

Example:
![error_example](https://github.com/user-attachments/assets/a6d4afae-e977-4f5b-b121-01c7fa7ec071)

After the fix:
![image](https://github.com/user-attachments/assets/f75b082d-6dd2-47a1-83bc-86d3f6861306)

2024-12-17 11:56 UTC, MiquelRForgeFlow approved these changes
The video captures are really nice.

2024-12-27 07:59 UTC, LoisRForgeFlow requested changes
Hi @RicardCForgeFlow 

I'am not able to reproduce the issue, I cannot set a different UoM in the first place because the error raises:

https://github.com/user-attachments/assets/0eca9cf9-83ce-4e40-a84b-8c04a59c50df

Can you indicate the steps to reproduce?

2024-12-27 09:26 UTC, RicardCForgeFlow commented
Hi @LoisRForgeFlow I found the error doing this:

https://github.com/user-attachments/assets/762471ce-32cb-4e47-bf7e-2d1a77e8c4fc



> Hi @RicardCForgeFlow
> 
> I'am not able to reproduce the issue, I cannot set a different UoM in the first place because the error raises:
> 
>  2024-12-27.08-58-50.mp4 
> Can you indicate the steps to reproduce?

2025-06-04 10:42 UTC, LoisRForgeFlow requested changes

2025-06-04 10:42 UTC, LoisRForgeFlow commented on mrp_multi_level/wizards/mrp_inventory_procure.py
> -        errors = []
@RicardCForgeFlow  I see, thanks for the video, could you still keep the multiple error handling? I think you can fix the issue without raising in the very first error.

2025-06-04 11:15 UTC, RicardCForgeFlow commented on mrp_multi_level/wizards/mrp_inventory_procure.py
> -        errors = []
![image](https://github.com/user-attachments/assets/b9d91ab4-903f-482b-9c24-f53c0a49c2a3)
You are right, just changing this works

2025-06-04 11:26 UTC, LoisRForgeFlow approved these changes
right on! thanks

2025-06-04 11:26 UTC, LoisRForgeFlow commented
/ocabot merge patch

2025-06-04 11:32 UTC, merged