Add new module MRP Repair reorder lines
OCA/manufacture pull request #154
Opened 2016-09-26 10:30 UTC by hurrinico

2016-09-26 15:05 UTC, tafaRU commented on mrp_repair_reorder_lines/README.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Put this inside https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst#configuration section

2016-09-26 15:06 UTC, tafaRU commented on mrp_repair_reorder_lines/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
Please avoid these lines

2016-09-26 15:07 UTC, tafaRU commented on mrp_repair_reorder_lines/__openerp__.py
> +    "website": "https://odoo-community.org/",
Please replace it by https://www.agilebg.com

2016-09-26 15:07 UTC, tafaRU commented on mrp_repair_reorder_lines/__openerp__.py
> +    "author": "Agile BusinessGroup,"
s/BusinessGroup/Business Group

2016-09-26 15:08 UTC, tafaRU commented on mrp_repair_reorder_lines/__openerp__.py
> +        "base",
Please remove it as redundant

2016-09-26 15:10 UTC, tafaRU requested changes
Also please add the OCA icon.
Thank you in advance.

2016-09-28 12:12 UTC, andhit-r approved these changes
LGTM :+1:

2016-10-03 08:31 UTC, hurrinico commented
@tafaRU i've done the requested changes

2016-10-04 07:42 UTC, eLBati commented
@hurrinico please ```commit --amend``` to restart travis build

2016-10-05 07:33 UTC, hurrinico commented
@eLBati Done 💃

2016-10-06 10:09 UTC, gurneyalex commented
@hurrinico I'm ok on the module, but the README needs updating. The usage section especially is not useful. Same thing for the HTML version of the readme.

2016-10-10 08:16 UTC, hurrinico commented
@gurneyalex i've chaged the usage section, but i don't understand what i've to change about HTML

2016-10-10 15:39 UTC, gurneyalex commented
@hurrinico you included the default template file, which needs filling in. I'd recommend maintaining only a correct README.rst file, otherwise you end up duplicating a lot of information which is against DRY. 

Parts which would need updating are 

* https://github.com/OCA/manufacture/pull/154/files#diff-24a1fa7869f73fa834b176a3c4c0a4b3R16 
* I'm pretty sure the sshot is not what you want https://github.com/OCA/manufacture/pull/154/files#diff-24a1fa7869f73fa834b176a3c4c0a4b3R25
* configuration: https://github.com/OCA/manufacture/pull/154/files#diff-24a1fa7869f73fa834b176a3c4c0a4b3R38
* usage: https://github.com/OCA/manufacture/pull/154/files#diff-24a1fa7869f73fa834b176a3c4c0a4b3R60
* ...

2016-10-11 09:19 UTC, hurrinico commented
@gurneyalex i'have made some changes to index.html file

2016-11-16 14:16 UTC, eLBati commented
@hurrinico I would remove index and keep README only

2017-07-31 09:09 UTC, hurrinico commented
@eLBati done

2017-08-07 06:33 UTC, eLBati requested changes
then, :+1:

2017-08-07 06:33 UTC, eLBati commented on mrp_repair_reorder_lines/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
@hurrinico if you add icon.png , con't add icon.svg

2018-01-11 09:05 UTC, tafaRU requested changes
Please squash 2 commits together for merging.

2019-09-30 13:05 UTC, lreficent commented
/ocabot merge

2019-10-01 12:33 UTC, lreficent commented
I tried to merge as it was green, but seems that after rebasing it is not. I will close as this is stale, please  reopen and fix it if you think it is still relevant.

2019-10-01 12:33 UTC, closed without merging