[ADD][8.0] mrp_production_raw_material_procurement_group
OCA/manufacture pull request #161
Opened 2016-10-22 15:45 UTC by andhit-r

===============================================
Create Procurement Group On Manufacturing Order
===============================================

This module adds ability to group manufacturing order's raw material moves, and
other moves created by it's pull flow, by given procurement group.

Usage
=====

To use this module, you need to:

1. Go to menu *Manufacturing -> Manufacturing -> Manufacturing Orders*
2. Create manufacturing order. Do not forget to fill *Raw Material Procurement Group*
3. When MO is confirmed. Raw material moves with *make to order* procurement method, and it's
   other moves created by it's pull flow, will be grouped based on *Raw Material Procurement Group*
   given

2016-10-26 01:35 UTC, m-sani commented
tested :+1:

2016-11-01 01:13 UTC, andhit-r commented
@mikevhe18 @azmimr67 please review

2016-11-02 07:22 UTC, mikevhe18 commented
:+1: Tested On Runbot

2016-11-11 09:01 UTC, jbeficent commented
Very useful @andhit-r . For my use case would be great to create a procurement group for each MO. I would build a separate module, right? (something such as mrp_production_raw_material_procurement_group_auto)

2016-11-11 09:16 UTC, andhit-r commented
@jbeficent i think i can do something for your use case. Wait for next my commit.

2016-11-13 05:48 UTC, andhit-r commented
@jbeficent i made some change to cover your use case. Would you kindly review it again. Many thanks.

2016-12-03 00:55 UTC, andhit-r commented
@jbeficent @lreficent would you kindly review this PR again. Many thanks.

2016-12-07 10:03 UTC, LoisRForgeFlow requested changes

2016-12-07 10:03 UTC, lreficent commented on mrp_production_raw_material_procurement_group/models/mrp_production.py
> +            self.raw_material_procurement_group_id = obj_group.create({
Wouldn't be better to call self._prepare_procurement_group before creating? That way we have better extensibility.

2016-12-07 10:03 UTC, lreficent commented on mrp_production_raw_material_procurement_group/tests/test_mrp_production.py
> +    def test_copy_mo_2(self):
Rename to test_group_name I think is more descriptive.

2016-12-14 08:30 UTC, jbeficent commented
@andhit-r, @lreficent will propose the improvements as a PR to your branch.

2016-12-15 02:09 UTC, andhit-r commented
@jbeficent @lreficent i did cherry-pick on @lreficent last commit (785b22ce03975613f75a54034e1240cea1eff5d0). This due conflict on https://github.com/andhit-r/manufacture/pull/2

Many thanks for revision.

2016-12-15 04:08 UTC, JordiBForgeFlow approved these changes

2016-12-15 04:10 UTC, merged

2016-12-15 04:11 UTC, jbeficent commented
cc @lreficent Can you start to port to v9?

2016-12-15 08:20 UTC, lreficent commented
Yes, I'll work in that.