[10] product quick bom
OCA/manufacture pull request #178
Opened 2017-02-15 16:35 UTC by EBII

This module was written to create quickly the bom for your product.
Indeed in the product form you now have a new tab "bom" that give you the posibility
to add the bom line directly here

2017-02-16 09:35 UTC, lreficent commented on product_quick_bom/README.rst
> +To install this module, you just need to install it
please remove not needed sections.

2017-02-16 09:35 UTC, lreficent commented on product_quick_bom/README.rst
> +No configuration is required
Also this one.

2017-02-16 09:35 UTC, lreficent commented on product_quick_bom/__manifest__.py
> +    "demo": [
remove empty keys.

2017-02-16 09:35 UTC, lreficent commented on product_quick_bom/__manifest__.py
> +    "external_dependencies": {
remove empty keys

2017-02-16 09:35 UTC, lreficent commented on product_quick_bom/__manifest__.py
> +    "version": "10.0.1.2.0",
Isn't this the first version to be merged in v10? Please update to 10.0.1.0.0.

2017-03-02 16:30 UTC, bealdav commented
please remove .pot file as defined in guideline

2017-03-06 14:59 UTC, Garamotte requested changes

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/bom.py
> +        'You can only have one Bom per product template',
Add `_()` around the error message to make it translatable.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/bom.py
> +        store=True)
I think you forgot to set this field `readonly=True`.
Also, please explicitely name all parameters (`comodel_name='product.template'`).

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/product.py
> +        'product_tmpl_id',
Explicitely name all parameters.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/product.py
> +            'product_tmpl_id': self.id,
Add `self.ensure_one()` as first line of the method to ensure you have only one record in self.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/product_view.xml
> +<data>
Remove `<data>` tag.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/product_view.xml
> +            <field name="priority" eval="200"/>
Defining the priority is really needed here ?

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/{repo_id}/{branch}
Replace `{repo_id}` by the real repo id and remove the comment.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/bom.py
> +from odoo import models, fields
Imports should be alphabetized.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/product.py
> +from odoo import models, fields, api
Imports should be alphabetized.

2017-03-06 14:59 UTC, sylvain-garancher commented on product_quick_bom/bom.py
> +class MrpBomLine(models.Model):
Split one file per model.

2017-03-07 09:46 UTC, EBII commented on product_quick_bom/product_view.xml
> +            <field name="priority" eval="200"/>
i don't know

2017-03-07 09:49 UTC, EBII commented on product_quick_bom/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/{repo_id}/{branch}
thanks

2017-03-15 11:07 UTC, bguillot commented on product_quick_bom/product.py
> +             'here the componant to product them')
s/you/your
add a space after "select"
s/componant/component
s/product/produce
s/them/it

And change the po file accordingly

Thanks !

2017-03-15 11:19 UTC, EBII commented on product_quick_bom/product.py
> +             'here the componant to product them')
replace by https://github.com/OCA/manufacture/pull/183

2017-03-15 11:19 UTC, closed without merging