[9.0] [MIG]  [mrp_bom_product_details]
OCA/manufacture pull request #187
Opened 2017-04-19 07:39 UTC by misern2

Bom product details
===================

This module adds product price and stock to bom view.

Usage
=====

* Go to Manufacturing > Products > Bill of Materials

2017-04-19 15:32 UTC, LoisRForgeFlow reviewed
Thank you for the contribution! Some comments:

2017-04-19 15:32 UTC, lreficent commented on mrp_bom_product_details/models/__init__.py
> +#########################################################################
Can you change to short headers? Follow the <a href="https://github.com/OCA/maintainer-tools/tree/master/template/module">template</a>.

2017-04-19 15:32 UTC, lreficent commented on mrp_bom_product_details/README.rst
> +No particular configuration to use this module.
Remove this section since it's not needed.

2017-04-19 15:32 UTC, lreficent commented on mrp_bom_product_details/README.rst
> +* http://en.wikipedia.org/wiki/File:People%27s_Action_Party_of_Singapore_logo.svg
Use the OCA logo following the template.

2017-04-19 15:32 UTC, lreficent commented on mrp_bom_product_details/views/mrp_bom_product_details.xml
> +    <data>
data tag can be removed

2017-04-19 15:32 UTC, lreficent commented on mrp_bom_product_details/views/mrp_bom_product_details.xml
> +			<field name="name">mrp.bom.tree</field>
Try to indent with four spaces.

2017-04-21 14:51 UTC, misern2 commented
Thank you for your comments @lreficent . It's been very useful. 👌

2017-05-30 09:42 UTC, cubells requested changes
Fast code review

2017-05-30 09:42 UTC, cubells commented on mrp_bom_product_details/README.rst
> +Bom product details
Follow this file https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst
please

2017-05-30 09:42 UTC, cubells commented on mrp_bom_product_details/README.rst
> +To install this module, you just need to select the module and insure yourself dependancies are available.
Line too long

2017-05-30 09:42 UTC, cubells commented on mrp_bom_product_details/__init__.py
> +from . import models
Newline is needed

2017-05-30 09:42 UTC, cubells commented on mrp_bom_product_details/__openerp__.py
>      'description': """
This key is not needed

2017-05-30 09:42 UTC, cubells commented on mrp_bom_product_details/__openerp__.py
>      'demo': [],
remove empty keys

2017-11-09 14:34 UTC, lreficent commented
@misern2 could you check travis?

2017-11-12 18:08 UTC, misern2 commented
@lreficent I updated my local branch and the Travis error was solved by commit  5f51684 

I'm not sure if it's the best way to proceed. Maybe a cherry peek with that commit it would be better.

2017-11-13 09:31 UTC, lreficent commented
@misern2 I see that you have added many commits related to other modules that shouldn't be here. Could you try to rebase against an updated OCA v9 branch? The the commit you are referring is already merged so it should be added with a proper rebase of your PR.

2017-11-13 16:14 UTC, misern2 commented
@lreficent  I made a rebase. The Travis build finally passed.

2017-11-14 09:12 UTC, lreficent commented
@misern2 Great, this is ready to review now! Thanks!

2017-11-14 09:13 UTC, LoisRForgeFlow reviewed
Some comments

2017-11-14 09:13 UTC, lreficent commented on mrp_bom_product_details/__openerp__.py
> +               "Odoo Community Association (OCA),QubiQ",
QubiQ is duplicated.

2017-11-14 09:13 UTC, lreficent commented on mrp_bom_product_details/__openerp__.py
> +    'license': 'GPL-3 or any later version',
Be consistent with headers: `"AGPL-3"`

2017-11-14 11:21 UTC, LoisRForgeFlow approved these changes
Tested on runbot, LGTM now :+1: 

Thanks!

2017-11-14 11:21 UTC, lreficent commented
@cubells Could you update your review, please?

2017-12-28 19:12 UTC, cubells requested changes
Minor changes. 

Ready to approve.

2017-12-28 19:12 UTC, cubells commented on mrp_bom_product_details/README.rst
> +yourself dependancies are available.
s/dependancies/dependencies/g

2017-12-28 19:12 UTC, cubells commented on mrp_bom_product_details/README.rst
> +   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
Change this line by

`:target: https://www.gnu.org/licenses/agpl`

as is indicated in https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2017-12-28 19:12 UTC, cubells commented on mrp_bom_product_details/__init__.py
> +# © 2015 - Solutions Libergia inc.
It's recommended to replace symbol © by `Copyright`

2017-12-28 19:12 UTC, cubells commented on mrp_bom_product_details/models/__init__.py
> +# © 2015 - Solutions Libergia inc.
It's recommended to replace symbol © by `Copyright`

2017-12-28 19:12 UTC, cubells commented on mrp_bom_product_details/models/mrp_bom_product_details.py
> +# © 2015 Oihane Crucelaegui - AvanzOSC
It's recommended to replace symbol © by `Copyright`

2018-01-02 20:06 UTC, misern2 commented
@cubells Can you update your review, please ?

Thanks!.

2018-01-03 06:40 UTC, cubells approved these changes
👍 

LGTM

Code review and test

2018-01-05 09:00 UTC, merged