[9.0][ADD] mrp_mto_with_stock
OCA/manufacture pull request #191
Opened 2017-04-26 16:44 UTC by lreficent

The author of this module is @michaeljohn32. I just adapt it to OCA standards, documented it and do minor fixes.

MRP MTO with Stock
==================

This module extends the functionality of Manufacturing to support the creation
of procurements when there is no stock available. This allow you to pull from
stock until the quantity on hand is zero, and then create a procurement
for fulfill the MO requirements.

Configuration
=============

To configure this module, you need to:

#. Go to the products you want to follow this behaviour.
#. In the view form got to the tab *Inventory* and check the box for the
   route *Make To Order + Make To Stock*.

Usage
=====

To use this module, you need to:

#. Go to *Manufacturing* and create a Manufacturing Order.
#. Click on *Confirm Production*.

2017-04-26 16:46 UTC, lreficent commented
@michaeljohn32 Do you think this is fine?

2017-06-07 13:09 UTC, AlainVanUtterbeeck commented
I did some testing and found a problem:
- we use a production zone, which is defined in the bom, so the system creates new moves on confirmation (a picklist to move the goods from stock to production). These moves are the ones that need to be verified for available and misssing stock instead of the original ones (which remain in state waiting till the picklist is issued), now the code does not handle this way of working.

2017-06-07 13:24 UTC, AlainVanUtterbeeck commented
@lreficent 
in mrp.py, adding these 3 lines fix the problem:

    @api.one
    def action_assign(self):
        """Reserves available products to the production order but also reates
        procurements for more items if we cannot reserve enough (MTO with
        stock).
        @returns list of ids"""
        # reserve all that is available (standard behaviour):
        res = super(MrpProduction, self).action_assign()
        # try to create procurements:
        for move in self.move_lines:

+            new_move = self.env['stock.move'].search([('move_dest_id','=',move.id)])
+            if new_move:
+                move = new_move

            if (move.state == 'confirmed' and move.location_id in
                    move.product_id.mrp_mts_mto_location_ids):
                domain = [('product_id', '=', move.product_id.id),
                          ('state', '=', 'running'),
                          ('move_dest_id', '=', move.id)]

2017-06-08 06:22 UTC, AlainVanUtterbeeck commented
@lreficent
Forget my previous remark please, it is not the solution.
I will continue testing...

2017-06-09 14:14 UTC, lreficent commented
@AlainVanUtterbeeck Ok, let me know whenever you find some issue :wink:

2017-06-09 14:52 UTC, mreficent commented
I think this module should have tests.

2017-07-23 05:15 UTC, jbeficent commented
@mreficent @lreficent added test cases, and minor fixes

2017-07-24 08:40 UTC, MiquelRForgeFlow requested changes

2017-07-24 08:40 UTC, mreficent commented on mrp_mto_with_stock/models/__init__.py
> -from . import mrp
then the `mrp.py` file should be deleted

2017-07-24 10:29 UTC, lreficent commented on mrp_mto_with_stock/models/__init__.py
> -from . import mrp
fixed @mreficent

2017-07-24 11:01 UTC, mreficent commented on mrp_mto_with_stock/README.rst
> +* John Walsh <?>
`<John.Walsh@interclean.com>`

2017-07-24 11:28 UTC, lreficent commented on mrp_mto_with_stock/README.rst
> +* John Walsh <?>
Thanks!

2017-07-24 12:08 UTC, MiquelRForgeFlow approved these changes
LGTM :+1:

2017-08-01 14:13 UTC, florian-dacosta approved these changes

2017-08-25 03:20 UTC, wangyueming commented
in mrp_production.py

I think 

`                        if qty_to_procure < move.product_uom_qty:
`

should be

`                        if qty_to_procure < move.product_qty:
`

2017-09-21 07:47 UTC, lreficent commented
This got merged in v10, can we move forward here too?

2017-11-09 09:52 UTC, lreficent commented
@OCA/manufacturing-maintainers can we get an update on this?

2018-02-01 16:52 UTC, jgrandguillaume approved these changes
LGTM

2018-02-01 16:53 UTC, merged