[9.0][MIG] quality_control
OCA/manufacture pull request #198
Opened 2017-05-24 15:26 UTC by lreficent

Continue the works started in https://github.com/OCA/manufacture/pull/100.

2017-06-12 11:27 UTC, MiquelRForgeFlow approved these changes
LGTM :+1: 
But I think some of the previous commits could be squashed.

2017-06-15 11:52 UTC, lreficent commented
Cherry-picked fix done in https://github.com/OCA/manufacture/pull/205/commits

2017-06-15 11:52 UTC, lreficent commented
Cherry-picked fix done in https://github.com/OCA/manufacture/pull/205

2017-06-27 13:53 UTC, andhit-r requested changes
Code review

2017-06-27 13:53 UTC, andhit-r commented on quality_control/wizard/qc_test_wizard.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/wizard/__init__.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/qc_trigger_line.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/qc_trigger.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/qc_test_category.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/qc_test.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/qc_inspection.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/product_template.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/product_product.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/product_category.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/models/__init__.py
> +##############################################################################
Change into short header

2017-06-27 13:53 UTC, andhit-r commented on quality_control/__init__.py
> +##############################################################################
Change into short header

2017-07-03 15:29 UTC, lreficent commented
Open PRs in v8:
* [ ] : https://github.com/OCA/manufacture/pull/193
* [ ] : https://github.com/OCA/manufacture/pull/213

2017-07-24 08:21 UTC, lreficent commented
@andhit-r Is this ok for you now? could you update your review?

2017-10-30 12:11 UTC, lreficent commented
@andhit-r ping

2017-11-09 09:52 UTC, lreficent commented
@OCA/manufacturing-maintainers can we get an update on this?

2017-11-13 18:25 UTC, damendieta commented
Hi, on creation of the Test Categories there there is an error that tries to compute the name but as It's a new record, the value is still false:

File "/mnt/extra-addons/manufacture/quality_control/models/qc_test_category.py", line 23, in _get_complete_name
    self.complete_name = " / ".join(reversed(names))
TypeError: sequence item 0: expected string, bool found

Replacing:
names = [self.name]
With:
names = [self.name or '']

Solves the issue.

Daniel.

2017-11-13 19:25 UTC, damendieta commented
Hi, I already fixed it and added some minor changes that I needed to test the module.

Also, could you please explain the logic of triggers on the readme, I coudn't find a way to make triggers work.

Thanks a lot.

2017-11-14 10:41 UTC, LoisRForgeFlow commented
Hi @damendieta 

First of all: thanks for your review!

Regarding the bug you reported, it is already being fixed in v8 and waiting to be ported to this PR after its merge, as noted here: https://github.com/OCA/manufacture/pull/198#issuecomment-312675900. Please review that PR (https://github.com/OCA/manufacture/pull/193) in order to move forward.

About the qc triggers, let me clarify that to make use of them you need either [quality_control_mrp](https://github.com/OCA/manufacture/tree/8.0/quality_control_mrp) or [quality_control_stock](https://github.com/OCA/manufacture/tree/8.0/quality_control_stock) modules. However, they still need to be migrated to v9.

Your help would be appreciated :wink:

2017-11-14 17:41 UTC, damendieta commented
@lreficent ok, I approved the PR #193, what else do we need for it to get merged?

2017-11-20 10:08 UTC, lreficent commented
@damendieta fix from https://github.com/OCA/manufacture/pull/193 added. Now you can review this PR and approve it if everything is ok for you.

2017-11-20 11:13 UTC, eLBati commented
@lreficent  hi, could you check commits like https://github.com/OCA/manufacture/pull/198/commits/e6d89619eeab5355d9c60887851c055b4a048acb with no message and unrecognised author?
Also please check if some commits can be squashed

2017-11-20 11:30 UTC, lreficent commented
Hi @eLBati  

It looks like "alfredo" has changed either his github email or name and that's why the author is unrecognized, however I don't know his current github account (If someone could point it to me I'll change the commit author accordingly). Regarding the squashing, I've already squashed consecutive transifex commits, I don't know if I can squash further since I'm not the author of any of the previous versions commits.

2017-11-20 11:34 UTC, eLBati commented
Maybe @oihane or @pedrobaeza know about his account?

2017-11-20 11:45 UTC, oihane commented
Alfredo de la Fuente's github user is alfredoavanzosc

2017-11-20 14:09 UTC, lreficent commented
@oihane Thanks!

@eLBati history has been fixed.

2017-11-20 16:05 UTC, eLBati approved these changes
Just a remark

2017-11-20 16:05 UTC, eLBati commented on quality_control/views/product_category_view.xml
> +<openerp>
Please use odoo

2017-11-21 09:19 UTC, SimoRubi reviewed
Just code review, looks good

2017-11-21 10:39 UTC, lreficent commented on quality_control/views/product_category_view.xml
> +<openerp>
Done, Thanks!

2017-11-21 10:42 UTC, lreficent commented
@SimoRubi Hi, please use the option to approve when submitting the review:
![selection_206](https://user-images.githubusercontent.com/23449160/33068279-000a4bc8-ceb1-11e7-994e-66900151dc62.png)

2017-11-21 10:43 UTC, lreficent commented
@damendieta If you are ok with this we can merge it I think

2017-11-21 10:44 UTC, SimoRubi approved these changes
Code review, looks good

2017-11-23 22:36 UTC, andhit-r approved these changes

2017-11-23 23:19 UTC, merged