[10.0] Migrate mrp_product_details
OCA/manufacture pull request #203
Opened 2017-06-03 12:42 UTC by bimajatiwijaya

2017-06-03 13:55 UTC, pedrobaeza commented
Please take the occasion to rename to singular: `mrp_bom_product_detail`

2017-06-04 00:22 UTC, elicoidal requested changes

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +This module adds information product price and product stock on bill of material tree view and bom component.
s/bom/BOM

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +This module adds information product price and product stock on bill of material tree view and bom component.
In general try to keep the sentences around no more 80 characters (nice to have)

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +To show price and product stock on bill of material, please apply product variant feature.
end the sentence with ":"

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +1. Go to Manufacturing > Configuration > Settings > Product Variants
better use the "#. " feature from rst for enumerated lines (nice to have)

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +   a. Tree view bom and component bom will show cost and stock.
the level is wrong, it should be something like:
```
#. Go to Manufacturing > Master Data > Bill of Materials
#. Tree view bom and component bom will show cost and stock.

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/__init__.py
> -import mrp_bom_product_details
Can you use short headers?

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/README.rst
> +* Bima Wijaya <bimajatiwijaya@gmail.com>
Are you the only contributor to the module?

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/__manifest__.py
>      'demo': [],
remove empty keys

2017-06-04 00:22 UTC, elicoidal commented on mrp_bom_product_detail/views/mrp_bom_product_details.xml
> +<odoo>
You can add copyright notice to xml if you wish

2017-06-04 00:50 UTC, pedrobaeza commented on mrp_bom_product_detail/README.rst
> +This module adds information product price and product stock on bill of material tree view and bom component.
Better BoM (Bill of Materials)

2017-06-04 09:13 UTC, bimajatiwijaya commented on mrp_bom_product_detail/__init__.py
> -import mrp_bom_product_details
i keep the header. Do you want to delete it ?

2017-06-04 10:49 UTC, andhit-r reviewed
LGTM. Waiting for header to adjust according OCA guidelines.

2017-06-04 10:49 UTC, andhit-r commented on mrp_bom_product_detail/__init__.py
> -import mrp_bom_product_details
What @elicoidal means is you should use short header format according to OCA guidelines. See https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py header's as an example. Pay attention to first 3 lines.

2017-06-05 11:40 UTC, andhit-r commented
@bimajatiwijaya i have no migrating experience yet. But i guess that change in module name will have an effect for old db that has this module installed. Won't we need migration script?

2017-06-05 11:43 UTC, pedrobaeza commented
That's simple achieve adding the renaming on OpenUpgrade on the file apriori.py. I'll do it directly when this gets merged.

2017-06-05 12:46 UTC, andhit-r approved these changes
Nice. LGTM.

2017-11-09 14:37 UTC, lreficent commented
@elicoidal could you update your review?

2017-11-10 01:34 UTC, elicoidal approved these changes
LGTM

2017-11-10 09:46 UTC, LoisRForgeFlow approved these changes
Code review LGTM

2017-11-10 09:47 UTC, lreficent commented
@bimajatiwijaya Could you squash your commits? We'll merge after it

2017-11-25 13:17 UTC, closed without merging

2017-11-25 13:46 UTC, bimajatiwijaya commented
@lreficent : i tried. i can't do squash. i create new pull request https://github.com/OCA/manufacture/pull/240