[9.0][ADD] mrp_split (WIP)
OCA/manufacture pull request #208
Opened 2017-06-08 12:26 UTC by lreficent

Responds to issue https://github.com/OCA/manufacture/issues/206

This is still a WIP and there are some points to improve/discuss (maybe more):
* [ ] Take into account consumable products.
* [ ] Picking direct validation lead to error. 

To reproduce this, follow these steps for instance:
1. In the manufacture route add a procurement rule to feed a location A with location Stock.
2. Create a procurement for location A of a manufactured product (MP) this will create a MO1 for MP and a picking from stock to location A.
3. Split MO1 and produce both, MO1 and new MO2.
4. Go to the picking created previously.
5. A) If you modify the the "Done" qty with all the "To Do" qty and click on validate you will be asked to create a backorder (with the qty in MO2).
5. B) If you click in validate and accept the immediate transfer you won't create a backorder and the MO2 is stuck. 

* [ ] Add security group related to splitting MOs?
* [ ] Cancelled stock moves are shown as consumed raw materials. This will require to modify a standard field, not sure if it is the good call.
![image](https://user-images.githubusercontent.com/23449160/26928429-5f0e8c52-4c56-11e7-8706-126742afb18d.png)

2017-06-23 17:02 UTC, andhit-r commented on mrp_split/README.rst
> +* Cancelled stock moves are shown as consumed raw materials.
@lreficent IMO you should not worry about cancelled stock moves. Just leave it there. Changing original field to hide cancelled move is not a correct move. Cancelled stock move information still needed on some case.

2017-06-23 17:26 UTC, andhit-r commented
**Functional Test 1**

1. Create procurement order manually for 5 unit of *[LAP-CUS] Laptop Customized*. A MO will be created automatically.
2. Confirm MO from step 1
3. Split into 2 unit

Original MO will have Product to Produce

![mrp-split-1](https://user-images.githubusercontent.com/1947376/27493319-a1e6ad24-5873-11e7-9b60-7d644b28e73f.png)

2017-06-23 17:27 UTC, andhit-r commented on mrp_split/models/mrp_production.py
> +        comodel_name='mrp.production', string="Backorder of", copy=False)
Make this field readonly

2017-06-23 17:53 UTC, andhit-r requested changes

2017-06-23 17:53 UTC, andhit-r commented on mrp_split/models/mrp_production.py
> +    backorder_ids = fields.One2many(
Make this field readonly

2017-06-26 08:19 UTC, lreficent commented
Hi @andhit-r and thanks for the review!

Yes, we had noticed that issue you mentioned. But, eventually we moved to a different approach to solve the issue related to this, see [mrp_production_request](https://github.com/OCA/manufacture/pull/210) which I think is ready to review (even with test added and all checks in green).

We don't have plans to works on this for the sort term, we have solved the issue with the module above, and this approach (as you suggested in the issue :wink: ) is quite tricky. Also, I guess this module would be difficult to keep alive in v10 due to big changes in standard mrp. However, if you are interested and you think this module is still a valid approach you can take it, I would love to review it and support!

2017-06-26 08:25 UTC, lreficent commented on mrp_split/models/mrp_production.py
> +        comodel_name='mrp.production', string="Backorder of", copy=False)
I will attend this.

2017-06-26 08:25 UTC, lreficent commented on mrp_split/models/mrp_production.py
> +    backorder_ids = fields.One2many(
I will attend this.

2019-06-03 09:19 UTC, lreficent commented
This can be closed, as this approach was abandoned in favor of mrp_manufacturing_request.

2019-06-03 09:19 UTC, closed without merging