11.0 mig mrp bom note
OCA/manufacture pull request #265
Opened 2018-04-19 07:47 UTC by agungrachmatulah

Migrating from v10 to v11 and adding unit test

2018-04-19 07:48 UTC, pedrobaeza commented
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2018-04-19 08:56 UTC, agungrachmatullah commented
@pedrobaeza i got this error in Travis-CI
![image](https://user-images.githubusercontent.com/6899025/38981604-fba87182-43e9-11e8-9853-c42986cb556c.png)
do you have any idea for this one?

2018-04-23 08:54 UTC, lreficent commented
Hi @agungrachmatulah 

Don't worry about that, just take care of the flase 8 issues: https://travis-ci.org/OCA/manufacture/jobs/368537220#L585-L590

Also, do not forget to squash commits as per @pedrobaeza suggestion.

Thanks for contributing!

2018-04-26 01:59 UTC, agungrachmatulah commented
Hello @pedrobaeza , i have rebase my commit. is there any problem with my commits?

2018-04-26 06:36 UTC, andhit-r approved these changes

2018-04-26 07:25 UTC, pedrobaeza commented
I still insist in squashing together adjacent "OCA Transbot..." + auxiliar commits 

![seleccion_002](https://user-images.githubusercontent.com/7165771/39291589-d180bbc2-4933-11e8-81f1-3867d5982f08.png)

2018-04-26 07:41 UTC, agungrachmatulah commented
Thanks for the hints.
I was thinking if that commit no need to fixup since its under your commit --> c7775a

2018-05-02 07:22 UTC, agungrachmatullah commented
Hello @pedrobaeza , is there anything missing from me?

2018-05-02 07:23 UTC, pedrobaeza commented
You need 2 approvals from reviewers. You can review other PRs and ask in exchange that they review yours.

2018-05-03 02:06 UTC, bimajatiwijaya approved these changes

2018-05-03 11:11 UTC, LoisRForgeFlow requested changes
Minor comments

2018-05-03 11:11 UTC, lreficent commented on mrp_bom_note/README.rst
> +No configuration required.
Remove empty section

2018-05-03 11:11 UTC, lreficent commented on mrp_bom_note/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/129/9.0
11.0

2019-10-14 07:55 UTC, LoisRForgeFlow approved these changes
Functional review :+1:

2019-10-14 07:55 UTC, LoisRForgeFlow commented
/ocabot merge

2019-10-14 08:34 UTC, merged