[10.0][ADD] quality_control_formula
OCA/manufacture pull request #330
Opened 2019-01-09 17:25 UTC by SimoRubi

New module to manage formulas in quality control.
Use case is the following: the value to be checked by the inspection is not what is inserted by the operator in Odoo but it is the result of some computation on that value (**input_value** in the module).

Such computation can also be performed based on the previous inspection lines of the same inspection.

2019-04-09 16:28 UTC, SimoRubi commented
Travis to be fixed with #346

2019-08-16 11:57 UTC, SimoRubi commented
@OCA/manufacturing-maintainers can someone please take a look? Thanks

2020-01-07 15:23 UTC, SimoRubi commented
@OCA/manufacturing-maintainers can someone please take a look?
How can I help this PR to be merged?
Thanks

2020-01-07 16:58 UTC, LoisRForgeFlow approved these changes
Code review, LGTM :+1:

2020-01-07 16:59 UTC, LoisRForgeFlow commented
@SimoRubi we still need one more review, maybe you can review other PR's and ask for a review here in exchange?

2020-01-23 16:14 UTC, tafaRU requested changes
Both technical and functional review.
Just some nitpicking otherwise LGTM. Thanks!

2020-01-23 16:14 UTC, tafaRU commented on quality_control_formula/i18n/it.po
> +msgstr "Formula Python formula per valutare la domanda del test.I valori disponibili sono 'input_value' e i valori di tutte le domande precedenti (il nome della variabile equivale al campo 'codice').
s/Formula Python formula/Formula Python

2020-01-23 16:14 UTC, tafaRU commented on quality_control_formula/models/qc_inspection_line.py
> +        for line in self:
it would be cleaner to use `self.filtered(lambda l: l.formula)`

2020-01-23 16:14 UTC, tafaRU commented on quality_control_formula/tests/test_quality_control_formula.py
> +        expected_res = (1 + 2 + 3) * 4
it would be better to get `3` as `int(inspection_line_d.quantitative_value)` likewise to when done for `inspection_line_c`.

2020-01-24 14:49 UTC, SimoRubi commented
Thanks @tafaRU for the review!
I implemented your suggestions, I didn't exactly get what you meant about the `tests` file..
Please check if that's ok now

2020-01-27 11:31 UTC, tafaRU commented
@SimoRubi thanks for the changes!

> I didn't exactly get what you meant about the tests file..

I meant to also calculate the result of the formula `A + B + int(input_value)` similarly to when done for the other one. It's non blocking comment anyway.

2020-01-27 11:32 UTC, tafaRU approved these changes

2020-01-27 11:54 UTC, LoisRForgeFlow commented
@SimoRubi are you going to add more changes or is it good to merge?

2020-01-28 11:39 UTC, SimoRubi commented
Hi,
I don't see our customer willing to modify this feature in next future so this is good to merge, thanks!

2020-01-29 10:36 UTC, LoisRForgeFlow commented
Let's do it then!

/ocabot merge

2020-01-29 11:17 UTC, merged