[12.0][MIG] mrp_multi_level
OCA/manufacture pull request #389
Opened 2019-08-05 13:34 UTC by lreficent

* You can know integrate with different forecasting mechanisms.
      As a consequence integration with stock_demand_estimate is moved
      to a new module (mrp_multi_level_estimate).
* As agreed by the authors, the module is re-licensed to LGPL-3.

@Eficent

2019-08-05 14:13 UTC, JordiBForgeFlow approved these changes

2019-08-09 12:39 UTC, HviorForgeFlow requested changes

2019-08-09 12:39 UTC, HviorForgeFlow commented on mrp_multi_level/models/product_mrp_area.py
> +    supply_method = fields.Selection(
'move' action has been split in v12 to pull, push pull_push.
This is causing errors on menu product mrp area parameters.

```ValueError: Wrong value for product.mrp.area.supply_method: 'pull'```

2019-08-12 08:18 UTC, lreficent commented on mrp_multi_level/models/product_mrp_area.py
> +    supply_method = fields.Selection(
Thanks for noticing, fixed.

2019-08-12 08:36 UTC, lreficent commented
@hveficent Could you update your review?

2019-08-13 12:41 UTC, HviorForgeFlow approved these changes
Code review
LGTM :+1:

2019-09-01 20:22 UTC, jbeficent commented
@lreficent can you check e5b2418 and backport to 11.0?

2019-09-02 09:50 UTC, lreficent commented
/ocabot merge

2019-09-02 10:21 UTC, lreficent commented
@jbeficent Tested, it works good and only runs current company areas if you manually do it from the wizard. Proceeding to merge.

/ocabot merge

2019-09-02 10:59 UTC, closed without merging