12.0 ADD module mrp_request_bom_structure
OCA/manufacture pull request #558
Opened 2020-11-16 17:44 UTC by bealdav

![Selection_115](https://user-images.githubusercontent.com/1853434/99288207-8b4a0e80-283b-11eb-9b69-82395d8d6bd0.png)

cc @florian-dacosta @hparfr @LoisRForgeFlow

2020-11-27 13:09 UTC, hparfr requested changes

2020-11-27 13:09 UTC, hparfr commented on mrp_request_bom_structure/models/mrp_request.py
> +        if not param or (param[0] != "{" and param[:-1] != "}"):
try except https://docs.python.org/fr/3/library/json.html#json.JSONDecodeError ?

2020-11-27 14:07 UTC, LoisRForgeFlow commented
wouldn't it be more "odooish" to place it under action dropdown?

2020-11-27 14:16 UTC, bealdav commented
It could be an option, but my client paid me this dev to avoid clicks. Dropdown make one more click.
If all users of this module want to go towards dropdown button, I have to override the view to add the button to directly click on it.

2020-11-27 15:21 UTC, LoisRForgeFlow commented
Got it, you are the only user for now so I guess you have the power :)

2020-12-04 07:56 UTC, bealdav commented
@LoisRForgeFlow please could make a final review, thanks.

I fixed code and have a better test coverage now

2020-12-04 13:10 UTC, dora-jurke approved these changes
Feature tested and working nicely

2020-12-04 13:30 UTC, thibaultrey approved these changes
Functionally reviewed

2020-12-04 14:04 UTC, marcelsavegnago approved these changes

2020-12-11 11:41 UTC, dreispt commented
/ocabot merge nobump

2020-12-11 13:07 UTC, bealdav commented
Thanks a lot @dreispt

2020-12-14 09:14 UTC, bealdav commented
Hi @dreispt could you try again ? Thanks

2020-12-17 08:54 UTC, bealdav commented
please @anajuaristi could you merge ?

2020-12-17 13:54 UTC, bealdav commented
please @dreispt could you try again ?

2020-12-24 07:58 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2020-12-24 09:18 UTC, bealdav commented
@LoisRForgeFlow FYI, I observe a random issue on v12 branch with mrp_subcontracting

![Selection_139](https://user-images.githubusercontent.com/1853434/103077882-f7552a80-45d0-11eb-95f4-5fd2e1c1c124.png)

Other topic, I fixed travils file on #579

2020-12-29 08:38 UTC, bealdav commented
Please @LoisRForgeFlow , now branch is completely fixed, could you try again ? ;-)
Thanks

2020-12-29 11:41 UTC, pedrobaeza commented
Merging blindly as request by @bealdav 

/ocabot merge nobump

2020-12-29 12:32 UTC, merged