[IMP] Partial subcontracting receptions
OCA/manufacture pull request #591
Opened 2021-01-29 16:48 UTC by ioans73

We have had some case in which we need to partially receive a subcontracting purchase order and current code does not allow it because if there is no quantity in the picking line, Odoo blocks the process (https://github.com/odoo/odoo/blob/12.0/addons/mrp/wizard/mrp_product_produce.py#L55). 

Another case, if we, for some reason, cancel the production order and the relations between movements and it are lost, 
it also blocks the process.

2021-01-29 16:56 UTC, pedrobaeza commented
This is a backport of v13 code, so... is this problem also in that version? If not, you should check the changes that have come on core from the merge date to now for allowing it. If yes, then you should propose the patch to Odoo core for not having again the constraint on next version.

2021-03-03 14:51 UTC, jado95 commented
@ioans73 I have the error that you linked also with this PR.

2021-03-03 15:23 UTC, jado95 requested changes
Can you add in if condition also `or move.quantity_done < move.product_uom_qty` for partially reception?

2021-03-04 09:33 UTC, ioans73 commented
We are going to proceed to close this PR, since finally the functionality that our client needs is different and we've taken another approach

2021-03-04 09:33 UTC, closed without merging