[14.0] [MIG] mrp_multi_level
OCA/manufacture pull request #592
Opened 2021-02-01 09:08 UTC by DavidBForgeFlow

Standard migration to v.14.

2021-02-26 11:57 UTC, HviorForgeFlow commented
Superseeds https://github.com/OCA/manufacture/pull/583

2021-03-01 11:24 UTC, LoisRForgeFlow requested changes
Commit history is lost. Follow process in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

2021-03-01 11:24 UTC, LoisRForgeFlow commented on mrp_multi_level/wizards/mrp_multi_level_views.xml
>  </odoo>
convert this to `<record ... model="ir.actions.act_window" ...`

2021-03-11 11:47 UTC, LoisRForgeFlow approved these changes
All looks good now!

2021-03-17 11:58 UTC, MateuGForgeFlow approved these changes

2021-03-17 11:59 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2021-03-17 13:21 UTC, merged