[14.0][ADD] repair_sale_order
OCA/manufacture pull request #735
Opened 2022-01-13 18:47 UTC by ChrisOForgeFlow

2022-01-19 09:30 UTC, LoisRForgeFlow commented
@ChrisOForgeFlow could you move this to the new specific repo for repairs? https://github.com/OCA/repair

2022-01-19 09:31 UTC, LoisRForgeFlow commented
> @ChrisOForgeFlow could you move this to the new specific repo for repairs? https://github.com/OCA/repair

well, actually I think v14 will still be in manfuacture, the transition will be done in v15. Sorry for the noise, to be considered on migration though :)

2022-01-19 11:25 UTC, AaronHForgeFlow requested changes
Overall it looks like a very useful module. I have a kind of an issue I think.

I created a repair type for sales. And then I created a repair order for a product and created the sale quotation from the repair order. I delivered the picking form the sales order and the repair order was set to "Repaired", that is fine. However, it seems those unwanted stock moves were created, aside from the picking of the sales order:

![image](https://user-images.githubusercontent.com/19620251/150120402-6be99ed4-f699-4721-b40b-bf39b887206e.png)

As far as I understand those stock moves are created automatically in the repair order. However, I cannot control the location for those stock moves, because in the repair type the location fields are hidden if I select "Create Sales Order". Also, the status of those stock moves are open after the repair order is set to "Repaired".

So, IMO, I would prevent the creation of those stock moves in this type of repair order. And I think if we can link the stock move of the picking of the sales order to the stock moves button in the repair order, that would be awesome. WDYT?

2022-01-19 13:25 UTC, ChrisOForgeFlow commented
> Overall it looks like a very useful module. I have a kind of an issue I think.
> 
> I created a repair type for sales. And then I created a repair order for a product and created the sale quotation from the repair order. I delivered the picking form the sales order and the repair order was set to "Repaired", that is fine. However, it seems those unwanted stock moves were created, aside from the picking of the sales order:
> 
> ![image](https://user-images.githubusercontent.com/19620251/150120402-6be99ed4-f699-4721-b40b-bf39b887206e.png)
> 
> As far as I understand those stock moves are created automatically in the repair order. However, I cannot control the location for those stock moves, because in the repair type the location fields are hidden if I select "Create Sales Order". Also, the status of those stock moves are open after the repair order is set to "Repaired".
> 
> So, IMO, I would prevent the creation of those stock moves in this type of repair order. And I think if we can link the stock move of the picking of the sales order to the stock moves button in the repair order, that would be awesome. WDYT?

This behavior is for this module

https://github.com/OCA/manufacture/blob/2b97a951241bf6d9878aecaaea4b0194d2777956/repair_stock_move/models/repair_order.py#L81

@LoisRForgeFlow Do you think this two modules should be compatible?

2022-06-21 10:43 UTC, MiquelRForgeFlow commented
please, could you rebase?

2022-12-02 08:49 UTC, AaronHForgeFlow commented
Rebased again to restart builds

2022-12-02 09:21 UTC, AaronHForgeFlow reviewed
Sorry for the late update here. My previous review is incorrect, so you can disregard it.

It looks good to me. Just a couple of minor comments and a question. I would like to include in the sales order also the possibility of include the operations services in the sales quotation. This is because the following use case:

- Customer returns the product out of warranty
- We spend time to investigate why it is broken
- We sell the spare parts so the customer can repair it but we also charge the cost of investigating the cause of the breakdown. 

Perhaps, if the repair type is sale, we can add another checkbox that says "include Operations". So the services can be included in the sales order as well. WDYT?

2022-12-02 09:21 UTC, AaronHForgeFlow commented on repair_sale_order/__manifest__.py
> +    "depends": ["repair", "repair_type", "sale", "sales_team"],
I think this should depend on repair_type and sale only, the others  would be implied dependencies

2022-12-02 09:21 UTC, AaronHForgeFlow commented on repair_sale_order/models/repair_order.py
> +                    "You should input almost one part line to"
```suggestion
                    "You should input at least one part line to"
```

2023-04-21 10:04 UTC, miguel-S73 commented on repair_sale_order/models/repair_order.py
> +            action["domain"] = action["domain"]
```suggestion            
            action["domain"] = action["domain"]
```

2023-04-25 14:48 UTC, miguel-S73 commented
@ChrisOForgeFlow please, fix pre-commit error.

2023-04-27 15:52 UTC, ChrisOForgeFlow commented
> @ChrisOForgeFlow please, fix pre-commit error.

Done!

2023-08-18 10:48 UTC, ferran-S73 commented
@ChrisOForgeFlow could you please rebase to generate runboat again?

2023-09-21 20:03 UTC, bosd approved these changes
Functional test, lgtm

2023-09-22 06:21 UTC, AaronHForgeFlow approved these changes

2023-09-26 07:39 UTC, LoisRForgeFlow approved these changes

2023-09-26 07:39 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2023-09-26 07:51 UTC, merged