[13.0][FIX] quality_control_oca: Protect product category view with group
OCA/manufacture pull request #858
Opened 2022-09-27 11:14 UTC by pedrobaeza

For avoiding access errors when other users without quality quality permissions wants to open the product category view.

@Tecnativa

2022-09-27 11:45 UTC, victoralmau requested changes

2022-09-27 11:45 UTC, victoralmau commented on quality_control_oca/views/product_category_view.xml
> +        <field name="groups_id" eval="[(4, ref('group_quality_control_user')])" />
```suggestion
        <field name="groups_id" eval="[(4, ref('group_quality_control_user'))]" />
```

2022-09-27 18:29 UTC, pedrobaeza commented on quality_control_oca/views/product_category_view.xml
> +        <field name="groups_id" eval="[(4, ref('group_quality_control_user')])" />
Done

2022-09-27 18:31 UTC, victoralmau approved these changes

2022-09-28 06:42 UTC, CarlosRoca13 approved these changes

2022-09-28 06:49 UTC, pedrobaeza commented
/ocabot merge minor

2022-09-28 06:54 UTC, merged