[ADD] smartlink on sale order to mrp_sale_info, directly copied from sale_mrp_link
OCA/manufacture pull request #861
Opened 2022-09-28 09:19 UTC by ntsirintanis

2022-09-28 13:56 UTC, thomaspaulb commented on mrp_sale_info/models/sale_order.py
> +        return action
For the sake of coverage, could you add a simple assert of `sale.production_count == 1` and a call to [action_view_production](https://github.com/OCA/manufacture/blob/12.0/mrp_sale_info/tests/test_mrp_sale_info.py#L39) in the tests here, asserting that the response in `res_id` is the production order we are expecting? It won't cover the `> 1` case, but it should already be a better coverage.

2022-09-28 14:04 UTC, thomaspaulb commented
@ntsirintanis Could you change tile to `[12.0][IMP] mrp_sale_info: ....` format

2022-09-28 15:00 UTC, thomaspaulb approved these changes

2023-01-11 16:26 UTC, NL66278 requested changes
Looks mostly good to me,  but black the added `mrp_sale_info/models/sale_order.py` to minimize the diff when forward porting. And because blacked code is nicer anyway.

2023-01-11 16:56 UTC, thomaspaulb commented
@NL66278 Makes sense, blacked it

2023-01-16 22:02 UTC, NL66278 approved these changes
:+1: LGTM

2023-03-09 13:35 UTC, gfcapalbo commented
:+1: LGTM

2023-03-09 13:36 UTC, thomaspaulb commented
@pedrobaeza This is the 12.0 version of https://github.com/OCA/manufacture/pull/943, can it be merged too?

2023-03-09 14:04 UTC, pedrobaeza commented
/ocabot merge major

2023-03-09 14:22 UTC, merged